version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: deeporigin
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: urlshortener
    ports:
      - "27017:27017"
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      MONGO_URL: mongodb://deeporigin:1234@mongodb:27017/urlshortener
      DB_NAME: urlshortener
      DB_USER: deeporiginusr
      DB_PASS: 123456
      DB_HOST: mongodb
      DB_PORT: 27017
      JWT_SECRET: 984263e1379af92bddbac0ba50201821b2
      SITE_URL: https://localhost:3000/
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data: